# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
      - master
      - next
  pull_request:
    branches: 
      - master
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rsuite: [4, 5]
        react: [16, 17]
        exclude:
          # RSuite 4 does not work with react 17
          - rsuite: 4
            react: 17
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- --coverage
      env:
        RSUITE_VERSION: ${{ matrix.rsuite }}
        REACT_VERSION: ${{ matrix.react }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: 'RSuite ${{ matrix.rsuite }} React ${{ matrix.react }}'