# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rsuite-version:
          - 4
          - 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- --coverage
      env:
        RSUITE_VERSION: ${{ matrix.rsuite-version }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: 'RSuite ${{ matrix.rsuite-version }}'