name: Release
on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - name: Semantic Release
        run: npx semantic-release
