name: Release
on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.10.5
      - run: pnpm i
      - name: Semantic Release
        run: pnpm semantic-release
